### ISSUE TITLE
Git submodule doesn't seem to be properly created

### ISSUE THREAD

**Issue by tpavlek** [homeyer/scoped-twbs#2]
After doing git submodule update (I assumed the npm submodule update was a typo in the readme), the bootstrap folder is empty. If I try to do a git fetch --tags, no tags are listed. I cannot checkout the 2.2.2 revision of bootstrap, which is what I need.

**Comment by homeyer** [comment]
Yup, looks like I missed a step. Try `git submodule init` and then `git submodule update`. I'll update the readme.
